# Generated by Django 3.1.7 on 2021-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='anchor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Якорь'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на внешний ресурс'),
        ),
    ]
