# Generated by Django 3.1.7 on 2021-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210329_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='status',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Для зарегистрированных'),
        ),
    ]
