# Generated by Django 3.1.7 on 2021-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='Заголовок')),
                ('sub_title', models.CharField(blank=True, max_length=800, null=True, verbose_name='Подзаголовок')),
                ('text', models.CharField(max_length=8000, verbose_name='Содержание')),
                ('edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовать?')),
                ('template', models.CharField(default='page/index.html', max_length=500, verbose_name='Шаблон')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='url')),
                ('registration_required', models.BooleanField(default=False, help_text='Если флажок установлен, то толькозарегестрированные пользователи могут проматривать страницу.', verbose_name='Требуется регистрация')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
