# Generated by Django 3.1.7 on 2021-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='Название')),
                ('text', models.CharField(max_length=8000, verbose_name='Содержание')),
                ('active', models.BooleanField(default=True, verbose_name='Вкл\\Выкл')),
                ('template', models.CharField(default='page/index.html', max_length=500, verbose_name='Шаблон')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
