# Generated by Django 3.1.7 on 2021-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='Если флажок установлен, то толькозарегестрированные пользователи могут просматривать страницу. ', verbose_name='Требуется регистрация'),
        ),
    ]
