# Generated by Django 3.1.7 on 2021-03-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210329_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования'),
        ),
    ]
