# Generated by Django 3.1.7 on 2021-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210309_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.CharField(default='blog/sport_list.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
