# Generated by Django 3.1.7 on 2021-03-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tag_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=True, verbose_name='Модерация пройдена'),
        ),
    ]
